### PR TITLE
Merge the nice features

### PR DESCRIPTION
**Pull request by Valcob**
Hey, could you please merge all the fixes and new features so we have all the latest and greatest in one place?

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Thanks for this - there are a few conflicts at the moment that would need resolving before the merge can continue

**Comment by Valcob** [comment]
Nice! thanks.

**Comment by chickey** [comment]
Hi Stuart, the url will need to be changed in loader.js as it points to the file on my github as it contained the UI changes.

**Comment by aussiegwapo** [comment]
Whats happening guys im confused. Will there be an update to bms

**Comment by aussiegwapo** [comment]
Whats happening guys im confused. Will there be an update to bms. Think im using colins code of the github of the bms script

**Comment by stuartpittaway** [comment]
> Hi Stuart, the url will need to be changed in loader.js as it points to the file on my github as it contained the UI changes.

Yes - fixed that in a further commit

**Comment by stuartpittaway** [comment]
> Whats happening guys im confused. Will there be an update to bms. Think im using colins code of the github of the bms script

This has merged colins code into the core base - both versions are the same/similar now.

I've also merged the "small" PCB design into the base and dropped the larger one.

**Comment by aussiegwapo** [comment]
Thats awesome as i have few aussies asking me about components for v3 as i did buy bulk supply in mofits and leds. 805s. Will update the code this weekend when i have time. 
Will it fix the page loading issue with in windows 10 due to not responding?

**Comment by stuartpittaway** [comment]
> Thats awesome as i have few aussies asking me about components for v3 as i did buy bulk supply in mofits and leds. 805s. Will update the code this weekend when i have time.
> Will it fix the page loading issue with in windows 10 due to not responding?

I'm not aware of the Windows 10 issue - can you raise an issue on Github please with some information on when it occurs?

**Comment by aussiegwapo** [comment]
Ok can do mite be a google brower issue. Not all the time. Could even be my wemos mini d1 issue. Hope soon to be adding my new d1 with esp32 wifi and shunt for solar to the mix as i have upgrade solar charege to esmart3 with wifi.

**Comment by chickey** [comment]
Hi Stuart were any other things not compatible from my modifications?

**Comment by stuartpittaway** [comment]
> Hi Stuart were any other things not compatible from my modifications?

Don't think so, seems to have merged easy enough.

**Pull request merged**
